from typing import Protocol, runtime_checkable

from vibra.domain.sync import EnrichedTrack


@runtime_checkable
class VectorStore(Protocol):
    """Protocol for vector database operations."""

    def add_track(self, enriched_track: EnrichedTrack) -> None: ...

    def add_tracks(self, enriched_tracks: list[EnrichedTrack]) -> None: ...

    def delete_tracks(self, track_ids: list[str]) -> None: ...

    def track_exists(self, track_id: str) -> bool: ...

    def search_by_vibe(self, query: str, n_results: int = 10) -> dict[str, list]: ...

    def get_all_tracks(self) -> dict[str, list]: ...

    def count_tracks(self) -> int: ...
